\pdfminorversion=4
\documentclass[a4paper]{article}
\usepackage{a4wide}
\usepackage[utf8]{inputenc}
\usepackage{lastpage}
\usepackage{fancyhdr}
\usepackage[section]{placeins}
\usepackage{hyperref}
\pagestyle{fancy}
\cfoot{\thepage\ of \pageref{LastPage}}


\title[FGCZ p\Sexpr{projectID} order \Sexpr{orderID}]{Functional Genomics Center Zuerich \Sexpr{projectID}  \\ Order: \Sexpr{orderID}: QC analysis for sample preparation and LC-MS}

\begin{document}

\SweaveOpts{concordance=TRUE}

\graphicspath{{/usr/local/lib/R/site-library/SRMService/samples/images/}{.}}

<<echo=FALSE, result=HIDE>>=
library(lattice)
library(xtable)
library(gplots)
library(affy)
library(missForest)
@
\maketitle


\section{Workflow Overview}

The general FGCZ LFQ workflow is described in Figure \ref{fig:workflowOverview}. Briefly:
proteins are precipitated using cold acetone, digested with trypsin and analysed via LC-MS/MS using high-end MS systems (e.g. Q-Exactive). The acquired raw files are processed using MaxQuant. The resulting text files are parsed and further processed to extract critical information on sample preparation and LC-MS performances (e.g. number of missed cleavages, correlation plots, protein identifications, quantitative values, ...).

\begin{figure}[!htb]
  \centerline{\includegraphics[width=0.8\textwidth]{LFQ_QC_workflow.pdf}}
  \caption{Shown is an Overview over the workflow how the following results are generated}
  \label{fig:workflowOverview}
\end{figure}


\pagebreak

\section{Data Input and Output Overview}

\subsection{Input: Samples analysed}
Here the list of acquired raw-files:
<<echo=FALSE, results=tex>>=
library(xtable)
# 2021-11-08 (jg): fix for changed structure in Summary.txt in new MQ version (not /2 anymore)
# NumFiles <- (nrow(summ))/2
NumFiles <- (nrow(summ))
files <- summ[2:NumFiles,1]
#myFileIndex <- 1:(NumFiles-1)
betterNames <- gsub(pattern = "^[[:digit:]]+_", replacement = "", gsub(pattern = "Intensity.", replacement = "", files))
evenBetterNames <- gsub(pattern = "^[[:digit:]]+_", replacement = "", gsub(pattern = "^[[:digit:]]+_", replacement = "", betterNames))
myFileTable <- as.matrix(cbind(as.character(files), evenBetterNames))
colnames(myFileTable) <- c("original RawFileNames", "Short Names")
print(xtable(myFileTable, caption="measured files"), size="\\normalsize", include.colnames=TRUE)
@


\pagebreak

\subsection{Parameters}


The protein identification and QC quantification was performed using MaxQuant.
Below are reported information about the MaxQuant version, the variable modifications taken into consideration, the database used and the targeted False Discovery Rate (FDR) at the spectrum (psm) and protein level. For the complete list of parameters please check the parameters txt file.\\


<<echo=FALSE>>=
#ParametersFile

#write out:
mqVersion <- paste(" ",params[1,2] ,sep="")
decoyMode <- params[3,2]
psmFDR <- params[18,2]
protFDR <- params[19,2]
varMods <- params[31,2]
fasta <- params[45,2]
enz <- unique(summ[2,4])
enzSpez <- unique(summ[2,5])
@

\begin{verbatim}
Maxquant version:  \Sexpr{mqVersion}

Fasta database:  \Sexpr{fasta}
Decoy mode:  \Sexpr{decoyMode}
Enzyme:  \Sexpr{enz}
Enzyme specificity:  \Sexpr{enzSpez}

Protein FDR:  \Sexpr{protFDR}
PSM FDR:  \Sexpr{psmFDR}

Variable modifications:  \Sexpr{varMods}
\end{verbatim}




\subsection{Overview of the data quality}
Information on the LC MS/MS data acquired for each sample:\\
- number of MS scans;\\
- number MS/MS scans;\\
- number of peptide sequences identified\\
\\

Data are extracted from file "Summary.txt"

<<echo=FALSE>>=
# 2021-11-08: (jg) fix for changed structure in Summary.txt in new MQ version (not /2 anymore)
# NumRows <- nrow(summ)/2
NumRows <- nrow(summ)
tt <- cbind(as.character(summ[1:NumRows,1]),as.character(summ[1:NumRows,17]),as.character(summ[1:NumRows,19]),as.character(summ[1:NumRows,24]),as.character(summ[1:NumRows,32]))

header <- tt[1,]
topTable <- as.table(tt[-1,])
filesHereInTable <- topTable[,1]
betterfilesHereInTable <- gsub(pattern = "^[[:digit:]]+_[[:alpha:]]+", replacement = "", gsub(pattern = "^[[:digit:]]+_", replacement = "", x = filesHereInTable))
topTable[,1] <- betterfilesHereInTable
# modify header
betterheader <- c("Raw file (short)", "MS/MS", "MS/MS submitted", "MS/MS identified", "Peaks sequenced")
colnames(topTable) <- betterheader
@


<<echo=FALSE, results=tex>>=
print(xtable(topTable, caption="Overview on the number of identified MS/MS spectra for each file."), size="\\small")

@
\pagebreak

\subsection{Protein identifications overview}
Next an overview about the number of proteinGroups is shown. We present here more information about the sequence coverage and how many peptides are identified.


<<echo=FALSE>>=
#ProteinGroups
#dat <- read.table(f, header=T, sep="\t")

#
# ff <- "maxquant/peptides.txt"
# pepts <- read.table(ff, header=T, sep="\t")
NumPep <- nrow(pepts)
#str(pepts)
# #total number of proteins
originalProteinGroups <-Fulldat
N <- nrow(originalProteinGroups)
bool_OneHitWonder <- originalProteinGroups$Razor...unique.peptides==1
bool_min2 <- originalProteinGroups$Razor...unique.peptides>1
bool_min3 <- originalProteinGroups$Razor...unique.peptides>2
ProtMin2 <- sum(bool_min2)
ProtMin3 <- sum(bool_min3)
averagePepPerProt <- round(mean(originalProteinGroups$Razor...unique.peptides),2)
medianPepPerProt <- median(originalProteinGroups$Razor...unique.peptides)
OneHitWonders <- sum(bool_OneHitWonder)
@

\begin{verbatim}
Total number of identified proteins:  \Sexpr{N}
Total number of protein only one single peptide:  \Sexpr{OneHitWonders}
Total number of protein with at least 2 peptides:  \Sexpr{ProtMin2}
Total number of protein with at least 3 peptides:  \Sexpr{ProtMin3}

Average number of peptides per protein:  \Sexpr{averagePepPerProt}
Median number of peptides per protein:  \Sexpr{medianPepPerProt}

Total number of unique identified peptides:  \Sexpr{NumPep}
\end{verbatim}


\subsection{Identified Peptide Sequences}
In the Maxquant output (evidence.txt) file there are informations for all identified peptides in the full experiment. In the Maxquant output (msms.txt) file there are informations for each and every identfied msms scan. We try here to show if all the files have been equally treated (e.g. same digestion efficiency, variable modifications..) \\

Shown is the distribution of picked and fragmented precursor masses for the different input files.

\begin{figure}[!htb]
<<echo=FALSE,fig=TRUE,width=12, height=8>>=
# handle again file names
evi_d$Raw.file <- gsub(pattern = "^[[:digit:]]+_", replacement = "", x = evi_d$Raw.file)
histogram(~ evi_d$m.z|evi_d$Raw.file, par.strip.text = list(cex = 1.2), xlab="precursors (m/z)", ylab="Perent of Total (%)")
@
  \caption{Distribution of the precursor m/z of the identified peptides}
  \label{fig:mzID}
\end{figure}

\begin{figure}
<<echo=FALSE,fig=TRUE,width=12, height=8>>=
histogram(~ evi_d$Mass.Error..ppm. |evi_d$Raw.file, nbins=50, main="Distribution of recalibrated mass error (ppm)", par.strip.text = list(cex = 1.2), xlab="Recalibrated mass error (ppm)")
@
  \caption{Distribution of recalibrated mass error (ppm) of precursors. Recalibration is a feature of MaxQuant.}
  \label{fig:ppmErrorCali}
\end{figure}

\pagebreak




<<echo=FALSE>>=
# handle again file names
msms_d$Raw.file <- gsub(pattern = "^[[:digit:]]+_", replacement = "", x = msms_d$Raw.file)
N <- length(table(msms_d$Raw.file))
@

% \begin{figure}[!htb]
% <<echo=FALSE,fig=TRUE,width=12, height=8>>=
% #Length Distribution over identified peptides (split on RAWfile)
% histogram(~ msms_d$Length|msms_d$Raw.file, main="Length Distribution of identified peptides", par.strip.text = list(cex = 1.2), xlab="Peptide Length")
% @
%   \caption{Overview of the peptide length for identified peptides (with respect to number of amino acids)}
%   \label{fig:Length}
% \end{figure}

\begin{figure}[!htb]
<<echo=FALSE,fig=TRUE,width=12, height=8>>=
#Missed cleavage
# Here Paolo requested a different plot -> I disagree and leave the trellis bar plot
N <- length(table(msms_d$Raw.file))
histogram(~ msms_d$Missed.cleavages|msms_d$Raw.file,main="Distribution of missed cleavages", par.strip.text = list(cex = 1.2), xlab="Number of missed cleavages")
@
  \caption{Overview for missed-cleavages for identified peptides}
  \label{fig:mmc}
\end{figure}

\begin{figure}[!htb]
<<echo=FALSE,fig=TRUE, width=12, height=15>>=
#VarMods
N <- length(table(msms_d$Raw.file))
#modPeps <- cbind(as.character(msms_d$Raw.file), as.character(msms_d$Modifications))
#table(modPeps)
#histogram(~ msms_d$Modifications|msms_d$Raw.file, main="VarMods per RawFile", layout=c(1,N), scales = list(x = list(rot = 90)))
# eventually take unmodified out? (ask Paolo)
histogram(~ msms_d$Modifications|msms_d$Raw.file, ylim=c(0,30), main="VarMods per RawFile",  scales = list(x = list(rot = 90, cex=0.8)), par.strip.text = list(cex = 1.2), xlab="Variable modifications")
@
  \caption{Overview of identified modifications for identified peptides (y-axis is truncated at 30 percent)}
  \label{fig:Varmods}
\end{figure}

\begin{figure}[!htb]
<<echo=FALSE,fig=TRUE,width=12>>=
#Charge
histogram(~ msms_d$Charge|msms_d$Raw.file, main="Distribution of Charges for identified peptides", par.strip.text = list(cex = 1.2), xlab="Charge of identified peptides")
@
  \caption{Overview of charge states for identified peptides. Note: Singly charged peptides are excluded for MS/MS. }
  \label{fig:Charge}
\end{figure}




%
%
%    HERE TO INSERT THE iRT SECTION ON LC STABILTY
%
%

\vspace{5cm}
\pagebreak


\section{QC of Quantitative Values}
\vspace{0.5cm}
<<echo=FALSE>>=

#filter for more than 2 peptides to use in quantitation -> we have to go back to original proteinGroups
# extract the columns that have unique and razor more than 1
# apply this bool to the IntenstiyMAT


#f <- matrixFileName
#f <- "proteinGroups_FGCZ2grp_Intensity.txt"
#dat <- read.table(f, header=T, sep="\t",row.names=1)
quantDat <- dat[bool_moreThanOnePeptide,]
QuantableProteins <- nrow(quantDat)

#write out:
totProteins <- nrow(dat)
msRuns <- ncol(dat)
grpSize <- ncol(dat)/2
dat_noZeros <- SRMService:::RemoveRowsWithZerosFromProtMatrix(dat)
matWoZeros <- nrow(dat_noZeros)
protsWithZeros <- totProteins - matWoZeros
protWihtOnlyOne <- totProteins - QuantableProteins
percQuant <- round((QuantableProteins*100)/totProteins,2)
@

\begin{verbatim}
Total number of proteins (MaxQuant, protFDR=5%) here is:  \Sexpr{totProteins}
--
Number of LC-MS/MS experiments included:  \Sexpr{msRuns}
--
Number of proteins with missing values:  \Sexpr{protsWithZeros}
Number of proteins without missing values: \Sexpr{matWoZeros}

Number of proteins with only one peptide: \Sexpr{protWihtOnlyOne}
Number of quantifiable proteins with more than ONE peptide: \Sexpr{QuantableProteins}

\end{verbatim}

\vspace{1cm}
This quality control of quantitative values section should show in the following figures, how the quantitative values for all the samples are distributed, correlated, imputed and normalized. To show the reproducibility among the different protein extracts we do a correlation of all quantitative values (pairwise) (see \ref{fig:normCorr}). The closer the correlation to ONE the better.


The input matrix has the following structure.\\
\begin{figure}[!htb]
<<echo=FALSE, fig=TRUE, width=6, height=10, results=hide>>=
#i_dat <- ImputeValuesInProtMatrixForRowsWithZeros(quantDat)
#n_i_dat <- NormalizeWithMedianPQMatrix(i_dat)

#image(asinh(t(dat)))
#axis(1,colnames(dat)[2], at = 2)
heatmap.2(asinh(as.matrix(quantDat)), dendrogram = "none", trace = "none", labRow="",margins=c(20,2), main="Heatmap of quantitative value\r in all experiments", ylab="proteins")
@
  \caption{Heatmap for all proteins with minimum two peptides (= quantifiable proteins) (Intensity value is hyperbolic arcsine transformed)}
  \label{fig:imagPlot}
\end{figure}




\begin{figure}[!htb]
<<echo=FALSE, fig=TRUE, width=6, height=8>>=
samples <- names(dat)
colors <- rainbow(length(samples))
#plotDensity(quantDat, xlim=c(0,2E11), col=colors, lwd=1, main="untreated SignalDistributions (no transformation)", xlab="(Quantitative value)")
maxY <- max(quantDat)/5
plotDensity(quantDat, xlim=c(0,maxY), col=colors, lwd=1, main="Distribution of untreated Signals (no transformation)", xlab="Quantitative value (x-axis is truncated)")
legend("topright", samples, text.col=colors)
@
  \caption{Density plot for quantifyable proteins (not transformed)}
  \label{fig:densityAsinh}
\end{figure}


\begin{figure}[!htb]
<<echo=FALSE, fig=TRUE,  width=6, height=8 >>=
plotDensity(asinh(i_dat), col=colors, lwd=1, main="Distributions of imputed signals before normalization", xlab="asinh(Quantvalue)")
legend("topright", samples, text.col=colors)
@
  \caption{Density plot of the quant values with imputation in asinh transformation (not yet normalized)}
  \label{fig:i_dens}
\end{figure}

\begin{figure}[!htb]
<<echo=FALSE, fig=TRUE,  width=6, height=8>>=
plotDensity(asinh(n_i_dat), col=colors, lwd=1, main="Signal Distributions (imputed and normalized)", xlab="asinh(Quantvalue)")
legend("topright", samples, text.col=colors)
@
  \caption{Density plot for normalized values based on imputed matrix (asinh)}
  \label{fig:normDensityPlot}
\end{figure}

The scaling factors are visualized in Figure \ref{fig:ScaleFactors}. It shows with what factor the individually calcuated numbers are boosted for the normalization.

\begin{figure}[!htb]
<<echo=FALSE, fig=TRUE, width=12, height=8>>=
#scaleF <- read.table(sf, sep=" ", header=F)
#sf <- "appliedScaleFactors_Median.txt"
par(mfrow=c(1,1))
par(mar=c(4,15,4,1))
barplot(scaleF$V2, horiz=TRUE, names.arg=scaleF$V1, cex.names = 1, las=1, main="Applied scaling Factors\n (for normalization)")
@
  \caption{Applied scaling factors for normalization (calculated using median normalization)}
  \label{fig:ScaleFactors}
\end{figure}





\begin{figure}[!htb]
<<echo=FALSE, fig=TRUE, width=12, height=8>>=

heatmap.2(as.matrix(cor(asinh(n_i_dat))),margin=c(15,10),trace="none", main="Pairwise sample Correlation")
#SRMService:::DoCorrelationOnMatrix(asinh(n_i_dat))
@
  \caption{Correlation plot for normalized values based on imputed matrix (asinh)}
  \label{fig:normCorr}
\end{figure}



\begin{figure}[!htb]
<<echo=FALSE, fig=TRUE, width=12, height=8>>=

pairs(asinh(n_i_dat), main="Pairwise Intensities vs Intensities Correlation", pch=".", col="blue")
#SRMService:::DoCorrelationOnMatrix(asinh(n_i_dat))
@
  \caption{All Signals against all samples (hyperbolic arcsine transformation)}
  \label{fig:pairPlot}
\end{figure}


\pagebreak

\section{Disclaimer and Acknowledgements}
This report is written by J. Grossmann using the \href{https://github.com/protViz/SRMService}{SRMService} package version \Sexpr{packageVersion('SRMService')} and processes text files which are exported from MaxQuant.\\
\\
ALL INFORMATION, INTELLECTUAL PROPERTY RIGHTS, PRODUCTS AND / OR SERVICES ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, SUITABILITY AND / OR FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN PARTICULAR, THE FGCZ (Functional Genomics Center Zurich, or any of its employees) MAKES NO WARRANTIES OF ANY KIND REGARDING THE ACCURACY OF ANY DATA, SOFTWARE, SCRIPTS AND / OR DATABASE.
\\
\\
Deep thanks go to C. Panse, S. Barkow, C. Trachsel, P. Nanni, C. Fortes and W. Wolski who provided stimulating environment, discussions and/or a template for this QC report.

\end{document}
